### ISSUE TITLE
support merge emty directory

### ISSUE THREAD

**Issue by mycf** [nvim-mini/mini.nvim#1217]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

less press `l`
<img width="301" alt="image" src="https://github.com/user-attachments/assets/bd7de221-5f42-4603-9589-e5a3727fdd8d">

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is not planned as I think this behavior is "too magical". See #1184 for a possible solution that makes "less press `l`" possible.
